# don't use spring boot's property anymore!!

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://accounts.google.com # replace with your own
spring:
  autoconfigure:
    exclude:
      # get rid of "Using default security password" logs and basic auth defaults
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Environment variables to use
# APP_ISSUERS_0_=https://accounts.google.com
# APP_ISSUERS_1_=https://auth0.auth0.com/
app:
  issuers:
    - http://localhost:8081/api/certificate/.well-known/jwks.json
    - http://dev-mbamc-bms-api.evotek.vn/iam/api/certificate/.well-known/jwks.json
